---
name: Build & Push Image to GHCR
on:
    workflow_call:
        inputs:
            name:
                description: The image name
                required: true
                type: string
            tags:
                description: The image tags
                required: true
                type: string
jobs:
    build-push-image:
        runs-on: ubuntu-latest
        steps:
            - name: Check out GitHub Repo
              uses: actions/checkout@v4

            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

            - name: Get current date for the tag
              id: tagdate
              run: echo "::set-output name=tagdate::$(date -u +'%Y-%m-%dT%H-%M-%S')"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  # note that the calling workflow must set `secrets: inherit`
                  username: '${{ github.actor }}'
                  password: '${{ secrets.GITHUB_TOKEN }}'

            - name: Create github action tags from image tags
              id: tags
              uses: actions/github-script@v7
              with:
                  result-encoding: string
                  script: |
                      const tags = '${{ inputs.tags }}'.split(',');
                      const username = '${{ github.event.repository.owner.login }}';
                      const repoName = '${{ inputs.name }}';
                      return tags.map((tag) => {
                        return `ghcr.io/${username}/${repoName}:${tag}_${{ steps.tagdate.outputs.tagdate }}`;
                      }).join(',');

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile
                  pull: true
                  push: true
                  build-args: |
                      BUILD_DATE=${{ steps.Zdate.outputs.date }}
                      VCS_REF=${{ github.sha }}
                      BRANCH='${{ github.ref }}'
                      TAG='${{ github.ref }}'
                  tags: '${{ steps.tags.outputs.result }}'
